### ISSUE TITLE
Other non-nougat Android versions not loading 

### ISSUE THREAD

**Issue by techydud** [Unzor/Nougat#2]
I can't use any other android versions then the nougat 7.0 and 7.1.

**Comment by Unzor** [comment]
Maybe refreshing your page will help. I tried it and it works for me for all versions of Android.

**Comment by techydud** [comment]
I tried multiple times, restarting, closing tab, reopening tab, nothing works.

**Comment by techydud** [comment]
Also, there isn't a home button.
